language: bash

# only build pushes to master
# prs are build separately
# https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built
branches:
  only:
  - master

services:
  - docker

matrix:
  include:
    - name: Linux Package
    - name: OSX Package
      os: osx
    - name: Windows Package
      os: windows

script:
  make test
