name: Check

on:
  workflow_dispatch
  schedule:
    - cron: '0 10 * * 2'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Rust Version
        run: make check
