name: Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 2'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      stable: ${{ steps.rust.outputs.stable }}
    steps:
      - uses: actions/checkout@v2
      - id: rust
        name: Check Rust Version
        run: make check
  create_issue:
    runs-on: ubuntu-latest
    needs: check
    if: always() && (needs.check.result == 'failure')
    steps:
      - uses: actions/checkout@v2
      - name: Create Issue 
        uses: bryannice/gitactions-git-issue-creation@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_REPO_OWNER: 'bryan-nice'
          GITHUB_REPO_NAME: 'github-issue-creation'
          GITHUB_ISSUE_TITLE: 'Demo''ing Git Issue Creation'
          GITHUB_ISSUE_BODY: 'Demo''ing Git Issue Creation'
