name: Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 2'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Rust Version
        run: make check
  create_issue:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.result == 'failure'
    steps:
      - uses: nashmaniac/create-issue-action@v1.1
        name: Create Issue Action
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          labels: rust-check-failed
          body: Update to rust stable version need.check.output.stable
