name: Main

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash
        run: make build
      - name: Publish Auth
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: make publish