name: Untrusted workflows (PRs)

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions/checkout@v1
      - name: Test
        run: make test